obj-$(CONFIG_FIH_INFO) += fih_info.o
obj-$(CONFIG_FIH_EMMC) += fih_emmc.o
obj-$(CONFIG_FIH_SEB) += fih_seb.o
obj-$(CONFIG_FIH_MFR) += fih_mfr.o
obj-$(CONFIG_FIH_TOUCH) += fih_touch.o
obj-$(CONFIG_FIH_RECAL_STATUS) += fih_recalibration_status.o
